version: '3.7'

services:

  pagejaune:
      restart: always
      build: .
      ports:
        - "3000:3000"

      depends_on:
        - mongodb
      environment:
        - MONGO_URI=mongodb
        - MONGO_PORT=27017
        - PORT=3000
        - DB=pdb
        - MONGO_INITDB_DATABASE=pdb

  mongodb:
      image: mongo
      ports:
        - 27017:27017
      environment:
        - MONGO_INITDB_DATABASE=pdb
      volumes: 
        - ./docker-entrypoint-initdb.d/initdb.js:/docker-entrypoint-initdb.d/initdb.js:ro
        - mongodb:/data/db

volumes:
  mongodb:
